### PR TITLE
Making exterior doors appear in the description of a RoomWithDoor

### PR DESCRIPTION
**Pull request by erikmartinessanches**
Previously, the exterior doors didn't appear in the description when we were inside a room with an exterior door.

### CODE REVIEW

**Comment by andrewstellman** [comment]
Thanks for catching this! If you're interested, I'm happy to send you draft PDFs of the upcoming 4th edition that we're still working on. I think we made some really nice improvements to the upcoming chapters.

**Comment by erikmartinessanches** [comment]
My pleasure, I'm enjoying the book and would happily continue practicing from the new draft and see if I catch any more mistakes.

**Comment by andrewstellman** [comment]
I just sent you an invite to a private repo. I hope you enjoy the new edition! It's in very good shape right now, but it's still a draft so definitely let us know if you find any mistakes.

**Comment by erikmartinessanches** [comment]
Thanks, I've accepted, yes will let you know if I spot any mistakes. Looking forward to checking out the new edition!

**Pull request merged**
